# Setting
spring:
  #JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  # jpa Query log
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method