server:
  port: 8900
spring:
  application:
    name: gateway-service
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true
        - name: LoggingFilter
          args:
            baseMessage: Logging Filter
            preLogger: true
            postLogger: true
      routes:
        - id: rank-service
          uri: lb://RANK-SERVICE
          predicates:
            - Path=/rank-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/rank-service/(?<segment>.*), /$\{segment}
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}

  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true